### ISSUE TITLE
Running Image in Docker Problem

### ISSUE THREAD

**Issue by AlaRuba** [nats-io/gnatsd#127]
Hi,

I'm trying to use Gnatsd in docker. In my docker-compose.yml, I specify it like so
```
gnatsd:
  image: apcera/gnatsd
  ports:
    - "4222"
    - "8333"
```
I then link to this image from the images that use it. However, when I try to connect in code like so
```
Sleep(5 * Second) //In case gnatsd isn't up yet
nc, err := nats.Connect(nats.DefaultURL)
	if err != nil {
		console.log(err.Error())
		return
	}
	ec, err := nats.NewEncodedConn(nc, nats.JSON_ENCODER)
	if err != nil {
		console.log(err.Error())
		return
	}
```
I get the following error
```
nats: No servers available for connection
```
I was wondering if I was connecting to it the right way via docker.

**Comment by wallyqs** [comment]
Hi, I believe in Docker Compose you have to specify both the host and container port so that it gets published: https://github.com/docker/compose/blob/master/docs/compose-file.md#ports
so I think you might be able to connect  if you set `4222:4222` in the ports section instead. Also you could try using the latest official image too `image: nats`.
