### ISSUE TITLE
Random Timeout in Request/Reply

### ISSUE THREAD

**Issue by dc0d** [nats-io/gnatsd#216]
Hi everybody! Could someone please help me with this https://play.golang.org/p/cfAAERFCer? I get timeout error randomly - it's a simple request-reply sample & I'm running nats with `gnatsd`.

**Comment by wallyqs** [comment]
Hi @dc0d, you are getting a `nats: timeout` because there are no Subscribers ready to reply by the time the requests are sent.
You might get better results by calling `Flush` after you `Subscribe` in the receiver side...

```go
        _, err = nc.Subscribe(subj, func(msg *nats.Msg) {
                cnt++
                replyMsg := fmt.Sprintf("from %v reply to request: %s", agentId, msg.Data)
                nc.Publish(msg.Reply, []byte(replyMsg))
        })
        err = nc.Flush()
        if err != nil {
                fmt.Println(err)
        }
```

but practically it is about making sure that there is at least a receiver by the time the requests are sent, in terms of this snippet a small wait before the requests are sent would help for example:

```go
        go rpl(1)
        <-time.After(100 * time.Millisecond)

        go req(1)
        go req(2)
        go req(3)
```
