### ISSUE TITLE
Introduce account concept

### ISSUE THREAD

**Issue by mcqueary** [nats-io/gnatsd#317]
An **account** encapsulates (and associates with) a set of users, a dedicated subject namespace, and dedicated multi-user subject authorization rules.

**Comment by steventanwc** [comment]
Yes. I concur with this. Currently NATS cannot be used in a secure authenticated way for multiple users whom may connect without us knowing their credentials prior to the start of the server.

We need the account so that users can be added dynamically without having the server to restart and be able to authenticate them.

**Comment by mcqueary** [comment]
Superseded by #347 & #348
