### ISSUE TITLE
Integrate Prometheus

### ISSUE THREAD

**Issue by mcqueary** [nats-io/gnatsd#345]
The server should integrate with [Prometheus](https://prometheus.io/) to allow easy alerting/visualization and other customization support.

**Comment by arekkas** [comment]
Yes that would be awesome! A lot of issues in distributed systems are due to partial errors or network errors and it would be great to have some native way of investigating these things. Maybe even some sort of plugin (coming with Go 1.8 iirc) feature that allows one to implement this logic.

Are there any more concrete plans for this?

**Comment by JensRantil** [comment]
A good start would be to simply expose the same metrics that can now be accessible over HTTP over the Prometheus format. Doesn't have to be complicated at all.

**Comment by ColinSullivan1** [comment]
Closing this since the [prometheus-nats-exporter](https://github.com/nats-io/prometheus-nats-exporter) has been introduced.

**Comment by nwest1** [comment]
Any possibility of reconsidering a prometheus endpoint being fully integrated with nats? 

Having to deploy/monitor/update yet another exporter component when prometheus has been adopted by a multitude of widely-used projects makes me wonder "why not?" and "pretty please?" 

Just a few: 
https://github.com/etcd-io/etcd/blob/master/Documentation/metrics.md
https://www.consul.io/api/agent.html#view-metrics
https://github.com/containous/traefik/blob/master/metrics/prometheus.go
https://www.envoyproxy.io/docs/envoy/latest/operations/admin.html?highlight=prometheus#get--stats-prometheus
