### ISSUE TITLE
client reconnect failed

### ISSUE THREAD

**Issue by chowyu08** [nats-io/gnatsd#355]
1.  when the router or cluster send end our info to the other side [here](https://github.com/nats-io/gnatsd/blob/master/server/route.go#L417) the infoJson only include ip:port , when the local nats-server down,  if the route other side  has the username and password , client will doReconnect failed.
could you modify the code [to](https://github.com/nats-io/gnatsd/blob/master/server/server.go#L896) add the username and password?

```
func (s *Server) getClientConnectURLs() []string {
	s.mu.Lock()
	defer s.mu.Unlock()

	sPort := strconv.Itoa(s.opts.Port)
	urls := make([]string, 0, 1)

	ipAddr, err := net.ResolveIPAddr("ip", s.opts.Host)
	// If the host is "any" (0.0.0.0 or ::), get specific IPs from available
	// interfaces.
	if err == nil && ipAddr.IP.IsUnspecified() {
		var ip net.IP
		ifaces, _ := net.Interfaces()
		for _, i := range ifaces {
			addrs, _ := i.Addrs()
			for _, addr := range addrs {
				switch v := addr.(type) {
				case *net.IPNet:
					ip = v.IP
				case *net.IPAddr:
					ip = v.IP
				}
				// Skip non global unicast addresses
				if !ip.IsGlobalUnicast() || ip.IsUnspecified() {
					ip = nil
					continue
				}
				if s.opts.Username == "" || s.opts.Password == "" {
					urls = append(urls, net.JoinHostPort(ip.String(), sPort))
				} else {
					url := s.opts.Username + ":" + s.opts.Password + "@" + net.JoinHostPort(ip.String(), sPort)
					urls = append(urls, url)
				}

			}
		}
	}
	if err != nil || len(urls) == 0 {
		// We are here if s.opts.Host is not "0.0.0.0" nor "::", or if for some
		// reason we could not add any URL in the loop above.
		// We had a case where a Windows VM was hosed and would have err == nil
		// and not add any address in the array in the loop above, and we
		// ended-up returning 0.0.0.0, which is problematic for Windows clients.
		// Check for 0.0.0.0 or :: specifically, and ignore if that's the case.
		if s.opts.Host == "0.0.0.0" || s.opts.Host == "::" {
			Errorf("Address %q can not be resolved properly", s.opts.Host)
		} else {
			if s.opts.Username == "" || s.opts.Password == "" {
				urls = append(urls, net.JoinHostPort(s.opts.Host, sPort))
			} else {
				url := s.opts.Username + ":" + s.opts.Password + "@" + net.JoinHostPort(s.opts.Host, sPort)
				urls = append(urls, url)
			}
		}
	}
	return urls
}
```

2.  if the two nats-servers have different tls (cert), how ?

**Comment by kozlovic** [comment]
1. It is intentional that the server does not return usernames and passwords in the connected URLs. Furthermore, we would not be able since we support multi-users.
Even if you decide to fork and do the above in your own repo, I need to warn you about the danger of doing the above. First, it is working only for single users, not multi-users. Also, think of this use case: server A has user userA/passA specified. Server B has userB/passB specified. These 2 servers are connected. A client that has the proper credentials to connect to A would then - with your change - receive credentials to connect to B. In other words, B would give away its credentials to clients that may not be meant to have them.
You should have the users defined on both servers with same credentials. Otherwise, in the above scenario, you would use the client UserInfo() or Token() API to provide credentials for URLs that the client gets from server auto-discovery.

2. The problem is the same than without auto-discovery. Suppose there is no auto-discovery and have a cluster of 2 servers (A and B) with different certs. You start a client with a URL that points to those 2 servers A and B. Same problem.

Note that you can always disable advertisement of server URLs to client by starting the server with:
`--no_advertise=false`
