### ISSUE TITLE
Clarify a NATS queue is fire-and-forget

### ISSUE THREAD

**Issue by JensRantil** [nats-io/gnatsd#406]
https://groups.google.com/d/msg/natsio/h-phVwNZTGA/6kubryIaDgAJ states that a NATS queue is "fire-and-forget". A common scenario to use a "queue" is to distribute work among workers in such was that work is distributed faster to the faster worker. Essentially, the worker pull tasks from the queue. This is not the case in core NATS. I propose this is documented in http://nats.io/documentation/concepts/nats-queueing/. Creating this issue because it took me a while to figure this out.

You might also want to refer to NATS Streaming for the pull version of a queue.

**Comment by glycerine** [comment]
@JensRantil: To me, the correct description of gnatsd is really as a "send-and-pray" system (like Erlang), whereas "fire-and-forget" is the exact opposite of what gnatsd provides.  There is nothing derogatory in these poetic descriptions. For an event-oriented system, like gnatsd -- that doesn't want to be shut down by slow consumers -- send-and-pray is most appropriate.

 My understanding of "fire-and-forget" is that it describes the situation where the client is allowed to fire the message off to the server, and then is allowed to forget about the message, because the server (gnatsd) will make delivery guarantees. Just like a missile that is launched and then needs to no further ground-control [1].

gnatsd, however, and the downstream delivery path, will readily discard any message if any internal buffers reach their limits.

Hence nats.io (without the nats-streaming-server part that does provide flow control) is distinctly NOT a fire-and-forget system.

[1] https://en.wikipedia.org/wiki/Fire-and-forget : "Fire-and-forget is a type of missile guidance which does not require further guidance after launch..."

**Comment by mcqueary** [comment]
@JensRantil Thanks for pointing out that our use of certain terminology may be confusing, especially when there are unaddressed assumptions in the minds of both the writer (us) and the reader (you). We will amend the documentation to describe these terms better in future.

We use the term _fire-and-forget_ to describe best-effort message delivery over TCP/IP, relying solely on the reliability features of TCP/IP, with no additional persistence at the application (NATS) layer. This means that neither the NATS client library nor the NATS server (`gnatsd`) take any steps to persist messages longer than the time it takes to write them over a TCP/IP socket from client->`gnatsd` or `gnatsd`->client.

The only exception to this is during periods that a client is attempting to reconnect to `gnatsd`. During a period of disconnection/attempted reconnection, supported clients will buffer outgoing messages until a connection is reestablished and the messages can be sent to `gnatsd`, or the reconnect buffer size is reached.

**Comment by gcolliso** [comment]
updated w/ PR339 nats-site
