### ISSUE TITLE
Knowing that there is no subscriber

### ISSUE THREAD

**Issue by mceaglens** [nats-io/gnatsd#422]
Is it possible to know (or easy to implement) that there is no subscriber on a certain subject?
If I haven't misunderstand to much, wouldn't it be easy for the nats server (to which we send the 
publish message) to answer with an error if there is no subscriber to a certain subject? If there is no local subscriber nor a route that is interested in the subject it would be quite easy to answer something?! At least in request/reply scenarios it could make sense to know that there never will be an answer,
it would  be possible to send something on the replyto subject.

What is your knowledge and opinion about this?

**Comment by ColinSullivan1** [comment]
Hi @mceaglens ,

By its nature, NATS is "fire and forget", so functionality like this hasn't been implemented in the server.  Instead, applications can implement this easily with request/reply.  You can make a request to the subject in question, with a timeout.  When a subscriber on the subject in question receives a message with a reply subject, it replies.  If the request times out, you'll know there are likely no subscribers, if it receives a reply, you know there is likely a subscriber on that subject.

If you are using golang, check out [nats-req.go](https://github.com/nats-io/go-nats/blob/master/examples/nats-req.go) and [nats-rply.go](https://github.com/nats-io/go-nats/blob/master/examples/nats-rply.go).  Other clients should have similar examples.

An alternative, aimed toward monitoring, would be to inspect subscriptions from `/connz` on the server monitoring url, but I'd suggest the method above if this is related to your application behavior.

Can you share more about your use case?

Regards,
Colin

**Comment by mceaglens** [comment]
Hi,
We use request/reply with timeout but have problem selecting the optimal timeout. It is a trade off between fast response time and waiting for time consuming actions or system at high load. That is why I examine if it would be possible to get some immediate indication from the server that there is no subscriber.

If I understood correctly it should be possible by the server to give this information as all subscriptions are replicated to all nats servers, right? If there is no local client nor any route that is interested in a certain subject it would be possible to send something, for example on the replyto subject? Or is this realy a bad idea? 

What about the monitoring endpoints, is it possible to see all the subscriptions? I only saw the number of subscriptions not the subjects themself! But I haven't examined it that much yet.
Regards
Magnus

**Comment by kozlovic** [comment]
@mceaglens Yes, it is easy for the server to know, but how can it "reply" to the sender? In the case of a request/reply, the reply that you provide is attached to a subscription that you have (or the `Request()` call has) created. If the server was to send a reply to that, it will be presented to the user callback. That can't be right.

In other words, without a protocol change, this is not possible. A NATS client does not wait for any acknowledgment back from the server, so the server has no where to send feedback to. Again, even in the case of a request/reply, the reply is for the application to receive application messages from the remote receiver, not "protocol" messages.

For the question about the monitoring, to get the actual list of subscriptions, you need to use the endpoint: `/connz/subs=1`.

**Comment by mceaglens** [comment]
ok, I agree, thanks.

**Comment by pananton** [comment]
Long time passed since this issue but I'd like to discuss it again. I'm using nats as a message queue connecting my microservices. Some operations are performed in a way when one microservice requests some information from others like this (A, B and C are microservices):
```
A --> B --> C
```

Suppose that C is dead. Then all requests from B will be waiting for a fixed timeout (1 second, 10 seconds, 1 minute?) We know that nats is lightning-fast, and B can send a  lot of requests to C during this timeout and each request probably will consume some resources on B as if it is under ddos attack from my own microservices. This can lead to situation when B will fail to process other requests (not involving C at all). Then other microservices sending requests to B (for example, A) start to experience timeout errors etc. What do you think, can such situation occurr?

**Comment by derekcollison** [comment]
We have been looking at ways that the system can let you know if it understands there was no interest available for delivery such that you do not have to wait for the timeout. However please note your app still has to deal with these types of problems that will be beyond NATS control. 

There are many ways to approach the problem, but the place to start is if C is mal-functioning what do you want the behavior of the system as a whole to be?

**Comment by pananton** [comment]
In my project (IM and video conferencing) its ok if part of the system is malfunctioning. In fact we are facing from time to time software errors leading to microservices crashes and it's not a big deal if the other parts are working and system keeps overall operability (errors can be treated in some automatic way, for example simply restarting malfunctioning service). What I'm afraid of is the situation when crashed microservice makes other parts behave poorly or even halt for the reasons I've described (for example, consuming a lot of resources awaiting responses from crashed microservice).
The solution can be, for example, to add new header similar to 'Reply-To' and containing subject to which nats server will publish a message (empty one) when it detects that there is no interest for a delivery.

**Comment by derekcollison** [comment]
Our thought was to reply with an empty payload if we detect no interest. This would be opt in of course.

**Comment by pananton** [comment]
Yeah, I think this will work also. Can you please notify me when you make your decision? I mean, whether you plan to add this feature or not.

**Comment by derekcollison** [comment]
Yes of course. This is part of a larger plan on system level services. For instance there already exists a low level system service that can be queried to see the status of all subscriptions on a matching subject across any NATS server topology, including super clusters.

**Comment by ArmorDarks** [comment]
That's an interesting topic. I wonder, was any decision made after all?

We have a case when one service tries to discover other services through NATS, whether any of them subscribed to a specific topic. It works well when there's at least one service since it will reply fast. However, if at the moment there are no subscribed services at all, we need to specify a timeout (like 1-10 seconds in our case). Since we need to make that discovery on each user request, it gets really slow when there are no subscribers due to the need to wait for timeouts.

The ability to immediately receive feedback from NATS that at the given moment there are no active subscribers would greatly improve that.

Just a random idea, maybe NATS can provide a built-in topic that will allow subscribing to subscription updates on the server? That way services will be able to know in advance whether anyone will ever reply to the message.

**Comment by derekcollison** [comment]
Modern servers for some time now will immediately respond to a request (a publish with a reply subject) if their are no known interest in the subject.

**Comment by ArmorDarks** [comment]
That's brilliant! Didn't know `request` works that way. Much obliged for a swift reply
