### ISSUE TITLE
Clustering failed in production

### ISSUE THREAD

**Issue by jbdalido** [nats-io/gnatsd#438]
Hi,

we had a weird issue on our 3 nodes production cluster earlier today, we started to see strange behavior on our applications, some messages coming in our cluster and obviously not ending up to the right clients. 

## INFOS :

- Gnatsd v0.9.6
- The applications are written in go and using the last version of the client 
- Kubernetes services are headless so not using any VIP 
- the cluster is full meshed, each node is configured with the routes of the two others node via the headless services (--routes nats-route://nodex:4244)

After checking the cluster we saw one node with twice less traffic than the two others. Last on checking the routes we also saw we had discrepancies around the value of :

```
"did_solicit": true,
"is_configured": true,
```

seeing sometimes true and false, both false etc ... the fact is we did not find reliable intels as what it means cluster wide.

Our cluster is running on a kubernetes cluster on GCE, and we restarted a node for whatever reason (two days ago). On one node on the /varz we can see that the connect url is still mentioning the previous container ipaddress :

```
"connect_urls": [
"10.128.3.68:4242", // This is the dead one
"10.128.2.70:4242",
"10.128.3.69:4242"
],
```

For debug and help, here's the dump of the /routes on each nodes

Node 1 :
```{
"now": "2017-02-18T14:36:26.612452889Z",
"num_routes": 2,
"routes": [
{
"rid": 11,
"remote_id": "Iw05J3RG56tC7wnpAb20Th",
"did_solicit": true,
"is_configured": true,
"ip": "10.128.3.69",
"port": 45155,
"pending_size": 0,
"in_msgs": 21361816,
"out_msgs": 6878987,
"in_bytes": 6326373766,
"out_bytes": 2375168042,
"subscriptions": 1759
},
{
"rid": 2,
"remote_id": "boWfGBXfB5bBZwpJyQmL2o",
"did_solicit": true,
"is_configured": false,
"ip": "10.128.0.6",
"port": 4244,
"pending_size": 0,
"in_msgs": 112443431,
"out_msgs": 75665634,
"in_bytes": 69469781532,
"out_bytes": 168047997129,
"subscriptions": 6188
}
]
}
```

Node 2 :
```
{
"now": "2017-02-18T15:01:32.838679187Z",
"num_routes": 2,
"routes": [
{
"rid": 14,
"remote_id": "Iw05J3RG56tC7wnpAb20Th",
"did_solicit": true,
"is_configured": true,
"ip": "10.128.3.69",
"port": 4244,
"pending_size": 0,
"in_msgs": 29877793,
"out_msgs": 38481507,
"in_bytes": 57812228994,
"out_bytes": 23569117081,
"subscriptions": 0
},
{
"rid": 2,
"remote_id": "95rnzP1ow4EGQ5A8ml67l8",
"did_solicit": false,
"is_configured": false,
"ip": "10.128.2.70",
"port": 33805,
"pending_size": 0,
"in_msgs": 76385872,
"out_msgs": 113596976,
"in_bytes": 169648956564,
"out_bytes": 70174005745,
"subscriptions": 0
}
]
}
```

Node 3 :
```
{
"now": "2017-02-18T14:36:24.509683332Z",
"num_routes": 2,
"routes": [
{
"rid": 1,
"remote_id": "95rnzP1ow4EGQ5A8ml67l8",
"did_solicit": true,
"is_configured": true,
"ip": "10.128.2.70",
"port": 4244,
"pending_size": 0,
"in_msgs": 6878874,
"out_msgs": 21361634,
"in_bytes": 2375131315,
"out_bytes": 6326321811,
"subscriptions": 4143
},
{
"rid": 2,
"remote_id": "boWfGBXfB5bBZwpJyQmL2o",
"did_solicit": false,
"is_configured": false,
"ip": "10.128.0.6",
"port": 55581,
"pending_size": 0,
"in_msgs": 38092390,
"out_msgs": 29620142,
"in_bytes": 23333074379,
"out_bytes": 57271891772,
"subscriptions": 6161
}
]
}
```

We switched back to a single node nats for now, and we are keeping this cluster in its current state for debug purposes and the follow-up of this issue.

Thanks in advance for the help !

**Comment by kozlovic** [comment]
@jbdalido It seems to me that this was all due to a server being restarted. Since it may have gotten a new IP (maybe `10.128.0.6`?) then it is why it is reported has not configured since the other servers did not have this ip in the `-routes` parameter. 
As for the "dead" server showing up in the `connect_urls` of the servers, this is expected. This array is cumulative of all servers that connected to a given server. The list is not updated when a server leaves, only when new ones are added.

**Comment by jbdalido** [comment]
@kozlovic thanks. After thinking the best way to be able to avoid this issue could be the use of a different advertise ip address

Right now if we define a `--cluster` to propagate the route, the server is also trying to bind on this address. instead we could use the `--cluster` as intended to listen/bind and define a `--cluster_advertise` to propagate the route to other nodes if specified.

Such configuration permit to use VIP addresses in front of potential dying containers (works for both swarm and kubernetes for example without the use of headless services). 

Ex :
```
 [...] --cluster_listen nats://0.0.0.0:4244 --cluster_advertise nats://10.131.254.103:4244 [...]
```

**Comment by kozlovic** [comment]
@jbdalido Just to be clear: what issue would you be solving with that?

To clarify: we use the term advertise for addresses clients can connect to. For instance there is a parameter that is `-no_advertise`, which prevents a server to send to its clients the client's listen info of other servers. The `connect_urls`, as you can see in the first comment of this issue, is an array that contains the urls clients (not servers) can connect to. Notice the port `4242` which is you client port, not the route port.

That being said, with auto-discovery, when a server accepts a route connection, it will indeed send to its already connected servers, the IP and port of the new server so that they can connect to this new server to form the full mesh. The address that is sent here is the result of `conn.RemoteAddr()`. I am guessing this is where you would want to use the address given in the command line as opposed to the address we get from the `RemoteAddr()` call. 

In the example you provide, is the `cluster_advertise` address not available to the host itself, and visible only from the outside? That is, why would you not provide it to `-cluster` parameter itself?

**Comment by kozlovic** [comment]
@jbdalido Could you review my last comment? Thanks!

**Comment by jbdalido** [comment]
Sorry missed your comment @kozlovic ! 

It's exactly that !

- The advertise ip is in fact only accessible from the outside of your machine and is being sent for the auto-discovery as a static route giving access to this instance. As u said instead of `conn.RemoteAddr()`, and then the instance is not trying to bind itself to it.
- The listen address is only here for the bind of the actual machine could be 0.0.0.0 on a container, or a special interface in a bare-metal cluster with private networking
- And finally yes, the advertise should be the only ip known by both other members of the mesh and clients, keeping the backend hidden.

This is the kind of setup we are actively using with cassandra or kafka for example.

Many thanks and sorry i was missing some key points in my explanation.

**Comment by kozlovic** [comment]
Closing this ticket in favor of #447. Thanks!
