### ISSUE TITLE
Provide binary for IBM Power LE (ppc64le)

### ISSUE THREAD

**Issue by Beilmann** [nats-io/gnatsd#555]
- [x] Feature Request

## Provide binary for IBM Power LE (ppc64le)

- Please compile the software on IBM Power LE (ppc64le) and provide the installable package for download.
- Please provide also docker image for IBM Power LE (ppc64le)

**Comment by kozlovic** [comment]
Building the executable for IBM Power LE (ppc64le) with manual cross compile is easy:
```
env CGO_ENABLED=0 GOOS=linux GOARCH=ppc64le go build -ldflags "-s -w" -o gnatsd
```
However, I don't think we could provide a docker image for that platform since I don't think that there is an official base image for POWER. One can publish an official image only if it is based on an official image or from SCRATCH.

**Comment by kozlovic** [comment]
We provide binaries as part of a release for hardware that we could test/debug on should an issue be reported. For that reason, we are not going to include an IBM Power LE binary in the next release.
Remember that you can always compile the binary yourself from source, either directly on the target platform or using cross-compilation as indicated above.
