### ISSUE TITLE
Is this a bug or not?

### ISSUE THREAD

**Issue by s921102002** [nats-io/gnatsd#558]
Hi All:
I got a strange problem, when subject is something like xx.9999,\*,\*,1, when sub and pub restart, sub cant't receive anything on xx.9999,\*,\*,1 it can be reproduce by following step, please notice the start and stop sequence
Env is 
Win7 x86
gnatsd 1.0.2
go-nats is lastest version by go get

1.start gnatsd  
2.start sub  
3.start pub   

*sub will receive 5 msg it's ok             
            
4.close pub  
5.close sub  
6.start sub  
7.start pub  

*now sub cant receive any msg..??  

8.restart gnatsd  
it's work again, but when follow step2 it's not working again.  
if the subscription is invalid, the api should return IsValid() = false??, but if it's invalid, why it works first time?

here is sample code  

sub code
```
package main

import (
	"fmt"

	"github.com/nats-io/nats"
)

func main() {
	nc, err := nats.Connect("nats://127.0.0.1:4222")

	s, err := nc.Subscribe("xx.9999,*,*,1", func(m *nats.Msg) {

		fmt.Println(string(m.Data))
	})
	fmt.Printf("s.IsValid()=%v\n", s.IsValid())

	fmt.Printf("Subscribe err=%v\n", err)
	nc.Flush()
	var buf string
	fmt.Scanf("%s", buf)
}

```

pub code
```
package main

import (
	"github.com/nats-io/nats"

	"fmt"
)

func main() {

	nc, _ := nats.Connect("nats://127.0.0.1:4222")

	for i := 0; i < 5; i += 1 {
		err := nc.Publish("xx.9999,*,*,1", []byte("test xx.9999,*,*,1"))
		fmt.Printf("publish err=%v\n", err)
	}

	nc.Flush()
	var buf string
	fmt.Scanf("%s", buf)
}

```

**Comment by kozlovic** [comment]
Are you intending to use the `*` characters as NATS wildcards? If so, the syntax is wrong since `*` should occupy a whole token and be separated by `.` (not commas). For instance, if you intended to use as wildcards, it would be `xx.9999.*.*.1`.
I am not sure if NATS should reject use of wildcards `*` and `>` when not used as wildcards (tokens separated by `.`). Regardless, I have been able to reproduce and I am investigating more to understand why it works the first time, and not after restarting the subscription. I will get back to you when I find what is going on. Thanks!

**Comment by kozlovic** [comment]
The problem is with the syntax of the subject. Some part of the code consider this subject be a two tokens 'xxx' and `9999,*,*,1`, but then some other parts, when it come to matching, report that `999,*,*,1` is not a literal (that is, subject without wildcard) simply because there is a wildcard (actually 2) in that section of the subject. So the old client connection is not removed from the cache. When a new message on subject `xxx.9999,*,*,1` is sent, the server find a cache entry for that and returns the old client information, which then causes the server to deliver to no one.
So back to the original question: if you intended to use wildcards, then you should use `.` not commas. If not, I believe that we should still fix that, which means that your subject will become invalid.

**Comment by s921102002** [comment]
Hi @kozlovic   

Thanks for your reply, I can change comma to dot in my usecase, I just want to confirm is this subject valid?  And I think if this subject is invalid then IsValid() should return false, or other people still confuse about it.

Thank you very much

**Comment by kozlovic** [comment]
I would say that the subject `xxx.9999.*.*.1` be valid, not `xxx.9999,*,*,1`. But the point of `*` is to be a wildcard and replace any string. I am not yet sure if this is how you meant to use it. For instance subscribing on `xxx.9999.*.*.1` would receive messages published on `xxx.999.foo.bar.1`, but not on `xxx.9999.foo.1`. Also, keep in mind that one cannot publish on wildcard subjects, so publishing on `xxx.9999.*.*.1` is not allowed.

About the `IsValid` in the subscription object, this function is meant to return false if the subscription or connection has been closed, not if the subscription is valid from a subject validity perspective.
Subscriptions are created asynchronously with the server, so the call to `Subscribe()` may not return an error even though the server is going to reject it. The error is sent asynchronously.

When creating the subscription, you would need to call `conn.Flush()` and then check `conn.LastError()` (instead of `IsValid()`). If we fix the server to reject this subject, that's how you would know that the subscription failed.

**Comment by s921102002** [comment]
Hi @kozlovic :  

Thanks for your reply.
In fact  I use \* not to do wildcards subscribe. I just treat it as a string . so I think the subject can be "9999,\*,\*" so I found this strange behavior and open this issue.
I think we should skip  . \* > and  space in subject, so if I want to use \* in subject maybe it should be replace  to '@ ' or other character.
In fact if use NATS as a broker, user publish a subject and we subscribe it from another data provider. we will meet this issue.  we can't define the subject should not contain some characters,  so in this situation, we  can only do a subject transform, but lost some performance.

Thank you very mush!

**Comment by tylertreat** [comment]
@kozlovic What is the technical reason `xxx.9999,*,*,1` is not valid? The way I see it, this subject has two literal tokens: `xxx` and `9999,*,*,1`. It seems like we should be able to split on `.` as we do and only treat `*` and `>` as wildcards and nothing else.
