### ISSUE TITLE
Notify the publisher(s) with the receiver(s) of their message(s)

### ISSUE THREAD

**Issue by amrnt** [nats-io/gnatsd#590]
I'm trying to find a way to implement a "read recipient" for the publisher. It means that whenever the publisher publishes a message, there would be a small message (configurable/contains subscriber info) sent from the subscriber notifying the publisher that the message was delivered.

I'm aware of `Request/Reply`, but I don't want the subscriber to explicitly send a reply. Also, I want to know what would prevent NATS to have it implemented into the server.

Thanks

**Comment by tylertreat** [comment]
IMO implementing it in the server would not be entirely useful because there is no guarantee the subscribers actually received/processed the message. By making the response explicit, you can guarantee whoever sent a response has received the message, which is a higher, end-to-end guarantee than if the server sent a response.
