### ISSUE TITLE
Feature: Support for iterating over queue contents

### ISSUE THREAD

**Issue by linux-support** [nats-io/gnatsd#715]
- [ ] Defect
 - [X] Feature Request or Change Proposal
 
 
#### Use Case:

When implementing service tools to manage queue contents it is required to have the opportunitity to iterate over queue contents without consuming messages. Other messageing / ESB systems name the feature 'peeking' message queues.

At the moment I could not find  a  feature like this in the source codes and the documenation. By utilizing workarounds you have to consume messages from the queue, evaluate them and reenqueue them. But this strategy has a number of downsides. It is error-prone and could lead to data loss.

#### Proposed Change:

Add methods to iterate / change / delete messages based on queues/subjects/channels.

 
#### Who Benefits From The Change(s)?

Every project required in managing enqueued data. E.g. service/admin frontends would be able to take a look into single messages without changing data or metadata of enqueued data.

#### Alternative Approaches

n.n.

**Comment by kozlovic** [comment]
Given the other issues you have opened, I believe that you have a misunderstanding of what NATS Server is and does. There is no queue in the traditional messaging term, the notion of queue is simply that a message is sent to only one of the many queue subscribers from the same queue group, as opposed to pub/sub where all consumers receive a copy of the message. In other words, queues allow you to load balance the processing of messages on a given subject/queue group.

For NATS Streaming, there is also no queue per-se, but a message log. Messages are not removed because they are consumed, they are removed (the old messages) based on the limits you can administratively set on a channel. So peeking at a channel is trivial in NATS Streaming since, again, messages are not removed because they are sent to consumers. Simply create a consumer at a specific message sequence in the channel to start receiving messages from that point. When you close, the subscription goes away (unless created as durable) but messages stay.

With that in mind, I am closing this and the other PRs that you have created.
