### ISSUE TITLE
Optimal count of connections for application

### ISSUE THREAD

**Issue by Sergey-Terekhin** [nats-io/gnatsd#787]
- [x] Question 
 - [ ] Defect
 - [ ] Feature Request or Change Proposal
 
Hi!
We have following question: Does optimal count of connections per application exist? Is it OK to have single connection for application or connection per topic should be created? Or something else?
Thanks for advice

**Comment by kozlovic** [comment]
You can certainly have a single connection for your entire application. Keep in mind, though, that if you have many different threads making publish calls, then this may produce lock contention. It may still be beneficial since the buffer send may accumulate more data (which help with throughput) than using multiple connections.
It all depends, really, and you should select based on your application requirements. Sometimes you need to have different connections because of authentication (different user/password, etc..).
