### ISSUE TITLE
Retention policy

### ISSUE THREAD

**Issue by yrsh** [nats-io/gnatsd#788]
I couldn't find any info about retention policy in queues, there no docs about it.
Could you please answer some questions:
1. Are there any limiting mechanism (maximum items number in queue or maximum memory usage, like in Hazelcast for example)
2. When messages are deleted? After read? After special timeout?
3. Can I specify TTL for items in queue?

**Comment by kozlovic** [comment]
There is no queueing at all in NATS Server. The notion of queue is simply that if you have subscriptions on the same subject and the same "queue" name, then a message is sent to only one of the member of the group, as opposed to pub/sub where all subscriptions on the subject gets the same message.

Something closer (but not even strictly equivalent to queueing the way you think about it) would be NATS Streaming: https://github.com/nats-io/nats-streaming-server
Like I said, even then, it is different in that messages are not removed because they are consumed. See https://github.com/nats-io/nats-streaming-server#subscriptions and https://github.com/nats-io/nats-streaming-server#queue-group.

**Comment by yrsh** [comment]
@kozlovic thanks for the explanation!
